### ISSUE TITLE
Adding Toolbar

### ISSUE THREAD

**Issue by ProgrammerBassam** [consp1racy/material-navigation-drawer#1]
I want to kbow how can I Add toolbar ??

**Comment by consp1racy** [comment]
Hi, add toolbar where?
- If you want a toolbar _INSIDE_ the navigation drawer, you'd have to add it as a header view. The list currently does not support custom views.
- If you want a toolbar _ABOVE_ the navigation drawer you can use the system action bar.
- If you want a toolbar _BEHIND_ the navigation drawer you need to include it in you layout. See http://android-developers.blogspot.cz/2014/10/appcompat-v21-material-design-for-pre.html for more details.
