### ISSUE TITLE
Make SimpleNavigationItemDescriptor not final

### ISSUE THREAD

**Issue by arneee** [consp1racy/material-navigation-drawer#4]
Hi,

I would like to extend SimpleNavigationItemDescriptor with some small custom information, but unfortunately it is final. Extending from BaseNavigationItemDescriptor would mean to copy a lot of code from SimpleNavigationItemDescriptor.

Thanks!

**Comment by consp1racy** [comment]
Hello,

the intention was to keep it simple, icon on the left, text in the middle and something on the right. `BaseNavigationItemDescriptor` is without the "something on the right" suitable for expansion.

**In next release the final modifier on `SimpleNavigationItemDescriptor` will be removed. This will however not be sooner than in three weeks.**

**For now please copy `SimpleNavigationItemDescriptor` to your project and modify it as needed.**

May I ask what would you like to add to the class? Perhaps it would make sense to even include it in the library. Thank you!

**Comment by arneee** [comment]
Hi,

Thanks for the fast reply! I will copy the class for now then. I just want to add some additional meta data. Without attaching it directly, I would have to make another array/list to store the id to meta data relationship.

Thanks!

**Comment by consp1racy** [comment]
Yes, another array would probably be the fastest option. Also it's completely independent of the navigation implementation. If the meta data doesn't affect the looks of the item, I'd consider this the true way to go.

Thank you for suggestions and good luck!
