### ISSUE TITLE
Is there a way to change the 12% transparency for selected items?

### ISSUE THREAD

**Issue by furyan87** [consp1racy/material-navigation-drawer#7]
I managed to change the background for selected items on the expanded drawer list but for the collapsed drawer, only showing the icons, I can't find a way to change the degree of transparency. Is there a way to change this?

**Comment by consp1racy** [comment]
Hello, thank you for pointing this out. It is currently not available, I'll work on it over the weekend.

**Comment by furyan87** [comment]
Great, thank you very much!

**Comment by consp1racy** [comment]
As of 0.7.6 you can use `activatedBackground*(...)` methods to specify item specific background color when selected. List selector still follows the `selectableItemBackground` attr from theme.
