### ISSUE TITLE
Meny SwitchCompat widgets in navigation-drawer 

### ISSUE THREAD

**Issue by willu2** [consp1racy/material-navigation-drawer#8]
I was add 20 items {.addItem(new ToggleNavigationItemDescriptor(*).checked(true))} into drawer. However, randomly other switches get switched once one is checked. Here is an example.

If I click on the first Switch: 9 is switched. 18 is switched. Then if I scroll all the way up, none are switched until 5. The next being 12.
How fix this? Thanks.

**Comment by consp1racy** [comment]
Just for you ;) I just pushed version 0.7.7 to jcenter which allows items to present themselves as "not recyclable". This will fix the incorrect state of ToggleNavigationItemDescriptor - they will not animate incorrectly as they come into view.
